language: php

php:
  - '7.2'
  - '7.3'
  - '7.4'

addons:
  mariadb: '10.3'

sudo: false

before_script:
  - composer install --prefer-source --no-interaction

before_install:
  - mysql -e 'CREATE DATABASE velkart_test;'
  - mysql -e "CREATE USER 'homestead'@'%' IDENTIFIED BY 'secret';"
  - mysql --user=root -e "GRANT ALL PRIVILEGES ON indiehd_test.* TO 'homestead'@'%' WITH GRANT OPTION;"
  - mysql --user=root -e 'FLUSH PRIVILEGES;'

services:
  - mysql

script:
  - mkdir -p build/logs
  - phpdbg -qrr vendor/bin/phpunit tests --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls -vvv
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL

after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL

notifications:
  email:
    #    recipients:
    #      - gtaylor@electricwerks.com
    #    on_success: always
    #    on_failure: always
    on_failure: change
